/** Generates a TypeScript module containing the WASM bytes, avoiding custom-protocol fetch. */

const [input, output] = Deno.args;
if (!input || !output) throw new Error("usage: embed-wasm <input.wasm> <output.ts>");
const encoded = (await Deno.readFile(input)).toBase64();
await Deno.writeTextFile(
  output,
  `/** Generated by plugin/wasm/build.sh. */\nexport const dashboardWasmBase64 = ${JSON.stringify(encoded)};\n`,
);
